server:
    port: 8761
spring:
    application:
        name: registry

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true
        hostname: localhost

logging:
    level:
        com.ead: DEBUG
        o.s.w.c.RestTemplate: DEBUG
        o.s.w.c.WebClient: DEBUG
        org.springframework.web.: DEBUG
        org.springframework.data.mongodb.core.MongoTemplate: DEBUG
        c.n.d.DiscoveryClient: DEBUG